### PR TITLE
adds note about spring

### PR DESCRIPTION
**Pull request by bdougie**
in reference to issue #9

### CODE REVIEW

**Comment by laserlemon** [comment]
I'm not very familiar with Spring (see [blog post](http://collectiveidea.com/blog/archives/2015/02/04/spring-is-dead-to-me/)) but is `spring stop` the best way to make this work? Wouldn't you want to start it back up again? Is there a `restart` or something?

**Comment by bdougie** [comment]
Interesting article: It briefly explains what spring is, a preloader for Rails that got [included with Rails starting Rails 4.1](http://guides.rubyonrails.org/4_1_release_notes.html#spring-application-preloader). I have been using it before then and it has sped up my workflow by allow commands such as `rails console`, `rake routes`, and `rspec your_spec.rb` to run much faster. It's a joy when TDD'ing a feature and need to frequently run a test.

To restart/start spring you just type `spring rails console`, `spring rake routes`, and `spring rspec your_spec.rb`. The first time you run spring it takes a normal amount of time, but after that, things spin much faster.

To the articles point, you have to run `spring stop` to clear the preloader when you add things like `Rspec::Wait`. You also have to run `spring stop` when you make changes to your models or data in your test, so spring can grab a fresh copy, which is where I think the frustration of that article comes from. You could have a failing test due to a change and continuing to run `spring rspec your_spec.rb`, but it will continue to fail until you actual stop and restart spring with `spring stop`. This can be very painful if you forget this while debugging your test. 

Let me know if my explanation makes sense.

**Comment by laserlemon** [comment]
Yeah, makes sense, thank you. I'm already too far gone on Spring so I won't be giving it another try any time soon. :stuck_out_tongue_winking_eye:

**Comment by laserlemon** [comment]
Shouldn't Spring already be watching the Gemfile by default?

**Comment by bdougie** [comment]
It does, but it preloads the gemfile and only updates what is cached after you stop and then start spring.

**Comment by laserlemon** [comment]
It seems as though Spring is supposed to watch `Gemfile` and/or `Gemfile.lock` and automatically restart when changed. From [Spring's readme](https://github.com/rails/spring#usage):

> If we edit any of the application files, or test files, the changes will be picked up on the next run without the background process having to restart. This works in exactly the same way as the code reloading which allows you to refresh your browser and instantly see changes during development.

> But if we edit any of the files which were used to start the application (configs, initializers, your gemfile), the application needs to be fully restarted. This happens automatically.

I'm going to close this issue with the understanding that it's Spring's responsibility to restart automatically after RSpec::Wait is added to the gemfile and the bundle is installed.

**Pull request closed without merging**
