### PR TITLE
support for RSpec 3.6

### PR DESCRIPTION
**Pull request by bertBruynooghe**
RSpec 3.6 is needed once you try to use spec_wait inside a rails 5 project.

### CODE REVIEW

**Comment by laserlemon** [comment]
Do you mean RSpec 3.5?

**Comment by bertBruynooghe** [comment]
Sorry, I meant RSpec 3.6 iso RSpec 2.6. I will update the above message accordingly.

**Comment by bertBruynooghe** [comment]
I am currently adding ruby 2.3 and rspec 3.6 to the forked travis configuration, and I seem to have to fix a few things still. Will come back soon.

**Comment by laserlemon** [comment]
I'm confused. I don't see RSpec 3.6 or a prerelease [on RubyGems.org](https://rubygems.org/gems/rspec/versions). I've opened up #17 if you want to take a look at what I'm doing there.

**Comment by bertBruynooghe** [comment]
My bad, so sorry. It is indeed 3.5, I got confused with the dependency declaring ```< 3.6```

**Comment by bertBruynooghe** [comment]
close this PR in favour of #17

**Pull request closed without merging**
